name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: invoicer/package-lock.json
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        working-directory: ./invoicer
        run: npm install

      - name: Prepare and deploy
        working-directory: ./invoicer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEMO_KEY: ${{secrets.DEMO_KEY }}
        run: |
          echo "export const environment = {" > src/environment.ts
          echo "  demoKey: '${{ secrets.DEMO_KEY }}'" >> src/environment.ts
          echo "};" >> src/environment.ts
          npm run ng -- deploy --base-href=/invoicer/ --name="Pelyn0" --email="tarasfall@gmail.com"
