name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: invoicer/package-lock.json
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Prepare and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run ng -- deploy --base-href=/invoicer/ --name="Pelyn0" --email="tarasfall@gmail.com"
